### ISSUE TITLE
Request to use libbcg729 with BSD license

### ISSUE THREAD

**Issue by alfredh** [BelledonneCommunications/linphone#102]
Hi,

In the baresip project (BSD license) we would like to add support for
G.729 codec using libbcg729 (GPL).

Would it be possible for you to grant us a liberal license, or
make an exception for the GPL ?

The PR is discussed here:

https://github.com/alfredh/baresip/pull/637

Thanks in advance,

Alfred

**Comment by smorlat** [comment]
Hi Alfred,

bcg729 is a software G729A/B encoder and decoder library written in C, developed by Belledonne Communications, available under open source (GPLv2) or proprietary license.
http://www.linphone.org/technical-corner/bcg729.html

If you need a proprietary license, for example to make a proprietary application that includes both baresip and bcg729, please contact Belledonne Communications.
http://www.belledonne-communications.com

Best regards,

Simon

**Comment by alfredh** [comment]
@smorlat Thanks for your answer :)

I will contact Belledonne then ..
