### ISSUE TITLE
Updating Linphone through flatpak fails with errors

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone#127]
On [this](https://www.linphone.org/technical-corner/linphone?qt-technical_corner=2#qt-technical_corner) page, you suggest installing Linphone via Flatpak.

Trying to update Linphone via Flatpak results in the following error messages:

```
F: Error updating remote metadata for 'linphone-origin': GPG signatures found, but none are in trusted keyring
F: Warning: Treating remote fetch error as non-fatal since app/com.belledonnecommunications.linphone/x86_64/4.1.1 is already installed: Unable to load summary from remote linphone-origin: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find app/com.belledonnecommunications.linphone/x86_64/4.1.1 metadata for dependencies: Unable to load metadata from remote linphone-origin: summary fetch error: GPG signatures found, but none are in trusted keyring
Nothing to do.
```
Can this be addressed?

Note: it looks like version updated anyway but hard to understand if there are problems, etc.

**Comment by traud** [comment]
Do you still face this issue?
As a workaround, what happens if you go for
`flatpak uninstall --user com.belledonnecommunications.linphone`
and then re-install Linphone again?

**Comment by stef204** [comment]
Did manage to uninstall and the reinstall and all is fine now.  I should have closed this issue a while back. Thanks.
