### ISSUE TITLE
Doxygen / pystache shouldn't be required when building without docs

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone#131]
Doxygen / pystache shouldn't be required when building linphone with `-DENABLE_DOCS=OFF`.
Currently this fails with this error message:
```
make[2]: *** No rule to make target 'coreapi/help/doc/doxygen/xml/index.xml', needed by 'wrappers/cpp/include/linphone++/linphone.hh'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:904: wrappers/cpp/CMakeFiles/linphone++.dir/all] Error 2
```

**Comment by KyronNextLevel** [comment]
Hi. As suggested in your log, doxygen is needed for the wrappers of linphone. There is no plans in removing this requirement in short term.

**Comment by lameventanas** [comment]
The point is that the rule runs even if one doesn't want any docs.
