### ISSUE TITLE
push service - very long time to run linphone in android

### ISSUE THREAD

**Issue by mahandra** [BelledonneCommunications/linphone#26]
Hello, 
we setup flexisip, push service, all work fine, but when I lclose app and service from android at all, (not in background mode), after that when i call to android, I got message from firebasemessaging:
see time when start  service and when start next step - mediaplayer after that start Activity
it long time approx 52sec.
after that Linphone starts
but 52 sec after calling so long.

08-14 16:12:58.171 9348-9348/org.linphone I/LinphoneService: text: %s registered
08-14 16:13:50.839 9348-9348/org.linphone D/MediaPlayer: setSubtitleAnchor in MediaPlayer

may be I incorrect flexisip?

what should I do?
Thank you!

 Debug linphone
08-14 16:12:53.914 9348-14095/org.linphone I/FirebaseMessaging: [Push Notification] Received
08-14 16:12:53.918 9348-9348/org.linphone I/LinphoneService:  ==== Phone information dump ====
08-14 16:12:53.919 9348-9348/org.linphone I/LinphoneService: DEVICE=generic_x86
                                                             MODEL=Android SDK built for x86
                                                             MANUFACTURER=Google
                                                             SDK=24
                                                             Supported ABIs=x86, 
08-14 16:12:53.919 9348-9348/org.linphone I/LinphoneService: Linphone version is 3.2.8 (3280)
**08-14 16:12:58.171** 9348-9348/org.linphone I/LinphoneService: text: %s registered
**08-14 16:13:50.839** 9348-9348/org.linphone D/MediaPlayer: setSubtitleAnchor in MediaPlayer
08-14 16:13:51.005 9348-9348/org.linphone V/FA: onActivityCreated
08-14 16:13:51.005 9348-9348/org.linphone I/LinphoneService: Activity created:org.linphone.LinphoneActivity@3705c68
08-14 16:13:51.068 9348-9348/org.linphone I/LinphoneService: Activity started:org.linphone.LinphoneActivity@3705c68
08-14 16:13:51.070 9348-9348/org.linphone I/LinphoneService: Activity resumed:org.linphone.LinphoneActivity@3705c68

**Comment by ReisBenjamin** [comment]
Hello,

Please open this issue on the correct repo : linphone-android.

Thanks
