### ISSUE TITLE
Lime Outgoing not working

### ISSUE THREAD

**Issue by droopy** [BelledonneCommunications/linphone#5]
I enable lime on the desktop compilation. 
Incoming chats works OK, but the outgoing ones do not add the previous zrtp hash, and are ALL in plain text.

In theory, If a lime enabled client try to send a message to a non lime-enabled one, the message won't be displayed and the sender will be notified that the message couldn't be delivered.
But this DO NOT WORK. I could send from a linphone lime enabled desktop client to another NON lime client (example jitsi) and the message could be delivered and received.
There is a bug there. Please check as seems LIme working ONE SIDE only. Incomings. But NOT outgoings.

**Comment by jeannotlapin** [comment]
Hi,
I cannot reproduce this problem. To enable lime, you shall enable it at build, but also manually set
lime=1
in the [sip] section of your .linphonerc config file, is it the case?

**Comment by droopy** [comment]
Yes, i enable LIME on the compilation.
I could received incomings ok, but the outgoings are in plain text always.
Try compiling it and send a chat to jitsi application, it will be received in plain text. In theory the delivery is blocked, but here works. Seems the outgoing code is missing.

**Comment by jeannotlapin** [comment]
Even with lime enabled you will always be able to receive plain text message.

To send encrypted messages, you must also enable lime in the linphone config file, not only on the compilation.

If lime is correctly enabled, your outgoing message mime type shall not be text/plain but xml/cipher which won't be accepted by jitsi.

**Comment by droopy** [comment]
Could you guide me on the path of the  .linphonerc config file, as it dont appear on my workspace. And do not exist on the github as filename

**Comment by jeannotlapin** [comment]
what is your platform?

The file is created the first time you run linphone.

On linux it should be in your home directory. On windows in your <user>/Application Data/Linphone directory.
