### ISSUE TITLE
zrtp mandatory option not working

### ISSUE THREAD

**Issue by droopy** [BelledonneCommunications/linphone#6]
Hi,
I would like to set zrtp as Mandatory in Preferences, Network Settings, Media Encryption type.
But that option is not clickable, while on SRTP is working.
Please fix this, so i could setup as mandatory
I could not do a direct zrtp call between 2 linphone desktops clients. Direct to direct.

regards.

**Comment by bagage** [comment]
See [faq](https://wiki.linphone.org/wiki/index.php/Faq#I_have_a_problem._How_to_get_logs.2Ftools.2Fcontacts_to_troubleshoot_the_issue.3F)

**Comment by droopy** [comment]
On faq i dont see the solution.
I could not do a direct zrtp call between 2 linphone desktops clients. Direct to direct.
As the zrtp is not mandatory option clickable.

**Comment by bagage** [comment]
It's not about the solution, it's about your bug report. We cannot guess what's your setup yet so please read FAQ and provide more information than "it's not working". Thanks.
