### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by bmutinda** [BelledonneCommunications/linphone#7]
I keep on getting this error when I try to call

``` java
linphoneCore.iterate();
```

Failed adding to JNI local ref table (has 512 entries)

Whenever I setup a new proxy address, I make sure I clear the existing one with the following code 

``` java
linphoneCore.clearAuthInfos();
linphoneCore.clearProxyConfigs();
linphoneCore.clearCallLogs();
```

The other thing am noticing is, whenever I add an account it seems the above code doesn't work hence creating many proxy configs. To see this, onregistration state I get several of them according to the number of times I have added my account.

Anyone with the best way to solve this??

Thanks

**Comment by tahirjilani** [comment]
@bmutinda 
were you able to resolve your issue?

**Comment by bmutinda** [comment]
@tahirjilani yes I did. This is what I did.
.I removed the existing account before adding a new one -- mostly when a user updates his settings
Let me just dump the code that I used to achieve this.

```java 
// Removing account 
try{
    LinphoneAuthInfo[] infos = linphoneCore.getAuthInfosList();
    for ( LinphoneAuthInfo info: infos){
        linphoneCore.removeAuthInfo(info);
    }
    LinphoneProxyConfig[] configs = linphoneCore.getProxyConfigList();
    for (LinphoneProxyConfig config: configs ){
        linphoneCore.removeProxyConfig( config );
    }

    linphoneCore.clearAuthInfos();
    linphoneCore.clearProxyConfigs();
    linphoneCore.clearCallLogs();
}catch (Exception e){
    e.printStackTrace();
}

// Adding account 

/**
 * ....... [Ommitted codes here to pull user profile and server settings]
 */

LinphoneCore linphoneCore = ZukuSipManager.getLinphoneCore();
LinphoneAuthInfo authInfo = LinphoneCoreFactory.instance().createAuthInfo(
        sipProfile.getUsername(), sipProfile.getPassword(), null, sipServer.domain );
linphoneCore.addAuthInfo(authInfo);
LinphoneAddress proxyAddr = null;
try {
    proxyAddr = LinphoneCoreFactory.instance().createLinphoneAddress(sipServer.proxy);
    proxyAddr.setTransport(LinphoneAddress.TransportType.LinphoneTransportUdp);
    LinphoneProxyConfig proxycon = linphoneCore.createProxyConfig(sipProfile.getAccId(), proxyAddr.asStringUriOnly(), proxyAddr.asStringUriOnly(), true);

    proxycon.enableRegister( true ); // Activate registration
    proxycon.setIdentity(sipProfile.getAccId() );
    proxycon.setProxy(sipServer.domain);

    linphoneCore.addProxyConfig(proxycon);
    linphoneCore.setDefaultProxyConfig(proxycon);
    proxycon.done();
} catch (LinphoneCoreException e) {
    e.printStackTrace();
}
```
Hope it helps you.
Thanks

**Comment by tahirjilani** [comment]
@bmutinda many thanks for the prompt reply.

I think my issue is different .it works fine if i make a call from Android to webrtc. Only issue happens if  I accept a video call from webrtc. Sometime call goes fine otherwise it crashes frequently. Perhaps it generates lot of stats update calls which break the system. 
i have my heads down.

thanks

**Comment by bmutinda** [comment]
@tahirjilani I haven't tried with video because I never needed it but maybe I should enable and give it a try.

**Comment by Wescoeur** [comment]
No longer relevant today.
